#!/bin/bash
# This shell snippet gives simple access to rca's floating point
# capability from a POSIX shell.  Use it with "source rca_float".
#
# Copyright (c) 2024-2026 Paul Fox <pgf@foxharp.boston.ma.us>
# SPDX-License-Identifier: BSD-2-Clause
#
# After including this code, use lines like this to calculate:
#       foo=$(fe "$bar * pi")
# or like this for a conditional expression:
#       if fc "(10 * 3) < $foo"; then ...
#
# Use RCA_INIT to set common initial conditions.  Defaults are
# provided here, but values set externally will override.
#
# Because the values stored by the shell are dependent on the display
# format that you configure with RCA_INIT, accuracy can degrade
# quickly during chained or looping calculations.  Good practice is to
# choose a precision at least 1 or 2 digits more than the application
# really needs.

export RCA_INIT_DEFAULTS="4digits fixed 1autoprint 0separators 1errorexit"

_rca_run()    # support routine
{
    local output exitcode

    output=$(
        RCA_INIT="$RCA_INIT_DEFAULTS ${RCA_INIT:-}" \
            rca "$*" q 2>&1
        )
    exitcode=$?

    # strip leading/trailing whitespace
    read -rd '' output <<< "$output"

    case $exitcode in
    0|1)
        echo "$output"
        return $exitcode ;;
    esac

    echo "rca failure: '$output'" >&2
    exit $exitcode
}

fe()    # Evaluate a floating point expression.
{
    _rca_run "( $* )"
    return 0
}

fc()     # Evaluate a floating point conditional expression.
{
    _rca_run "( $* )" >/dev/null
}

fe_rpn()    # Evaluate an RPN expression.  (Useful for "sum", or "avg".)
{
    _rca_run "$*"
    return 0
}

fp()
{
    echo $1
}
